scenario = "uplink_bridge"
bridge.name = "br-lan"
bridge.addr = "10.10.10.1/24"
bridge.ports[] = "eth1"
uplink.ifname = "eth0"
routes.default.dst = "0.0.0.0/0"
routes.default.via = "10.10.10.254"
routes.default.dev = "br-lan"
routes.peer.dst = "1.2.3.4/32"
routes.peer.dev = "br-lan"
